version: '3.5'
services:
  ngnix:
    container_name: ngnix
    build: ./requirements/nginx/
    restart: always
    volumes:
      - WordPress:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"         
    networks:
      - mynetwork

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    restart: always
    volumes:
      - WordPress:/var/www/html
    networks:
      - mynetwork
    env_file: .env
    depends_on:
      - mariadb


  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    restart: always
    networks:
      - mynetwork
    volumes:
      - db:/var/lib/mysql
    env_file: .env

# NETWORK
networks:
  mynetwork:
    name: mynetwork
    driver: bridge

# VOLUME
volumes:
  db:
  WordPress:
